import { 
  BeachBall, BowlingBall, BoxingGlove, Check, Code, Football, Golf, Hockey, Volleyball,
  HandPalm, HandFist, Lightning, Star, Heart, Sun, Moon, Bed, Airplane, Alarm, Alien,
  Anchor, Car, Champagne, Calendar, CalendarHeart, BuildingOffice, Broadcast, BatteryCharging,
  Asclepius, Chat, ChefHat, CigaretteSlash, Cheers, Cow,
  CurrencyDollar
} from "@phosphor-icons/react"

export const backPattern = [
  BoxingGlove,
  Football,
  Golf,
  BeachBall,
  BowlingBall,
  Hockey,
  Volleyball,
  Code,
  Check,
  HandPalm,
  HandFist,
  Lightning,
  Star,
  Heart,
  Sun,
  Moon,
  Bed,
  Airplane,
  Alarm,
  Alien,
  Anchor,
  Asclepius,
  BatteryCharging,
  Broadcast,
  BuildingOffice,
  CalendarHeart,
  Calendar,
  Car,
  Champagne,
  Chat,
  ChefHat,
  CigaretteSlash,
  Cheers,
  Cow,
  CurrencyDollar,
]
